---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-lib
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/ksemele/flux-lib
  ref:
    # branch: main
    branch: f/lib-init
