---
apiVersion: source.toolkit.fluxcd.io/v2
kind: OCIRepository
metadata:
  name: grafana
  namespace: grafana-operator
spec:
  interval: 24h
  url: oci://ghcr.io/grafana/helm-charts/grafana-operator
  ref:
    tag: v5.22.0
